config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: "home#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :foods do
    delete 'delete_food', on: :member
  end


  resources :recipes do
    member do
      patch 'toggle_privacy'
    end
  end

  resources :recipe_foods

  get '/shopping_list', to: 'shopping_list#show'

  get 'general_shopping_list', to: 'shopping_list#index'
  get 'public_recipes', to: 'public_recipes#index', as: 'public_recipes'

  get 'new_food', to: 'foods#new', as: 'custom_new_food'
  get 'new_recipe', to: 'recipes#new', as: 'custom_new_recipe'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :ingredients
  belongs_to :user
  validates :measurement_unit, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :food
end

app/models/measurement_unit.rb
class MeasurementUnit < ApplicationRecord
  has_many :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients, class_name: 'Ingredient'
  has_many :recipe_foods
  validates :name, presence: true

  def toggle_privacy
    self.public = !public
    save
  end

  def count_ingredients
    ingredients.count
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :recipes

  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, :set_food, only: [:destroy]

  def new
    @food = Food.new
  end

  def index
    @foods = current_user.foods.includes(:ingredients)
    @food = current_user.foods.build
  end

  def show
    @food = Food.find(params[:id])
    redirect_to foods_path
  end

  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully added.' }
      else
        format.html { render :index }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food item was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete food item.'
      redirect_to foods_path
    end
  end

  def delete
    @food = current_user.foods.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      redirect_to foods_path, alert: 'Food deletion failed.'
    end
  end

  def delete_food
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end



  private

  def set_food
    @food = current_user.foods.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipe = Recipe.all
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def show
    @recipe_foods = RecipeFood.where(recipe_id: params[:id]).includes(:food, :measurement_unit)
  end

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_food][:recipe_id]

    if @recipe_food.save
      flash[:notice] = 'Ingredient was successfully added to the recipe.'
      redirect_to recipe_path(@recipe_food.recipe_id)
    else
      flash.now[:alert] = 'Something went wrong! Ingredient was not added to the recipe.'
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(@recipe_food.recipe_id)

    if @recipe_food.destroy
      flash[:notice] = 'Ingredient was successfully removed from the recipe.'
    else
      flash[:alert] = 'Something went wrong! Ingredient was not removed from the recipe.'
    end

    redirect_to recipe_path(@recipe.id)
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id, :measurement_unit_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, flash: { success: 'Recipe saved successfully!' }
    else
      render :new, flash: { error: 'Recipe failed to save!' }
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    unless @recipe.user == current_user
      redirect_to recipes_path, flash: { error: 'You are not authorized to perform this action.' }
      return
    end

    if @recipe.destroy
      redirect_to recipes_path, flash: { success: 'Recipe deleted successfully!' }
    else
      redirect_to recipes_path, flash: { error: 'Failed to delete the recipe!' }
    end
  end

  def toggle_privacy
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.toggle_privacy
      redirect_to recipe_path(@recipe)
    else
      redirect_to root_path, alert: 'You do not have permission to do this.'
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :find_user

  def index
    @user = current_user
    @total_foods = 0
    @total_price = 0
    @recipe_foods = []

    @user.recipes.includes(recipe_foods: :food).each do |recipe|
      # Assuming you have a many-to-many relationship between Recipe and RecipeFood
      recipe.recipe_foods.each do |recipe_food|
        # Calculate the total quantity and price for each recipe_food
        quantity = recipe_food.quantity
        price = recipe_food.food.price * quantity

        # Add to the total count and price
        @total_foods += quantity
        @total_price += price

        # Add to the recipe_foods array
        @recipe_foods << { food: recipe_food.food, quantity:, price: }
      end
    end
  end

  private

  def find_user
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def set_default_role
    self.role ||= :user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: @recipe_food, url: recipe_foods_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.collection_select :recipe_id, Recipe.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :food_id %>
    <%= form.collection_select :food_id, Food.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/index.html.erb
<h1>Recipe Foods</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Recipe</th>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.quantity %></td>
        <td><%= recipe_food.recipe.name %></td>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.measurement_unit.name %></td>
        <td><%= link_to 'Show', recipe_food %></td>
        <td><%= link_to 'Edit', edit_recipe_food_path(recipe_food) %></td>
        <td><%= link_to 'Destroy', recipe_food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Recipe Food', new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>Add Ingredients</h1>

<%= render 'form' %>


app/views/recipe_foods/show.html.erb
<h1>Recipe Foods</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Recipe</th>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.quantity %></td>
        <td><%= recipe_food.recipe.name %></td>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.measurement_unit.name %></td>
        <td><%= link_to 'Show', recipe_food %></td>
        <td><%= link_to 'Edit', edit_recipe_food_path(recipe_food) %></td>
        <td><%= link_to 'Destroy', recipe_food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Recipe Food', new_recipe_food_path %>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, url: recipes_path, local: true, class: 'my-3' do |form| %>
  <h2 class="mb-3">Add Recipe</h2>
  <div class="field">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, name: "recipe[name]", class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :preparation_time, class: 'form-label' %>
    <%= form.number_field :preparation_time, name: "recipe[preparation_time]", class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :cooking_time, class: 'form-label' %>
    <%= form.number_field :cooking_time, name: "recipe[cooking_time]", class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, name: "recipe[description]", class: 'form-control' %>
  </div>

 <div class="field">
  <div class="form-check">
    <%= form.radio_button :public, true, name: "recipe[public]", class: 'form-check-input' %>
    <label class="form-check-label">
      Public
    </label>
  </div>
  <div class="form-check">
    <%= form.radio_button :public, false, name: "recipe[public]", class: 'form-check-input' %>
    <label class="form-check-label">
      Private
    </label>
  </div>
</div>

  <div class="actions">
    <%= form.submit 'Add Recipe', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1 class = "text-center">Recipes</h1>

<% if @recipes.empty? %>
  <h2>There are no recipes created yet</h2>
<% else %>
  <ul>
    <% @recipes.each do |recipe| %>
      <li class = "flex">
        <div>
        <h3><%= link_to recipe.name, recipe %></h3>
        <%= button_to 'Delete Recipe', recipe, method: :delete, data: { confirm: 'Are you sure you want to delete this recipe?' }, class: 'btn btn-success', remote: true %>
        </div>
        <div>
        <label>Description:</label>
        <p><%= recipe.description %></p>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="container">
  <h1><%= @recipe.name %></h1>
  <div class="row">
    <div class="col-md-6">
      <p><strong>Preparation Time:</strong> <%= @recipe.preparation_time %> minutes</p>
    </div>
    <div class="col-md-6">
      <p><strong>Privacy:</strong>
        <%= form_for @recipe, url: toggle_privacy_recipe_path(@recipe), method: :patch do |f| %>
          <div class="form-check toggle_btn form-switch">
            <%= f.label :public, @recipe.public ? "Private" : "Public", class: "form-check-label", for: "public-toggle" %>
            <%= f.check_box :public, class: "form-check-input", id: "public-toggle", onchange: "this.form.submit()" %>
          </div>
        <% end %>
      </p>
    </div>
  </div>
<div class="col-md-6">
      <p><strong>Cooking Time:</strong> <%= @recipe.cooking_time %> hours</p>
    </div>
  <div class="row">
    
    <div class="col-md-6  margin_f">
      <%= link_to 'Generate Shopping List', general_shopping_list_path, class: 'btn btn-primary float-start' %>
      <%= link_to 'Add Ingredients', new_recipe_food_path, class: 'btn btn-success' %>
    </div>
  </div>

  <h2>Ingredients</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td>
            <% if recipe_food.food.price.present? && recipe_food.quantity.present? %>
              $<%= recipe_food.food.price * recipe_food.quantity %>
            <% else %>
              Price unavailable
            <% end %>
          </td>
          <td>
            <%= button_to 'Delete', recipe_food, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>