config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: "home#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :foods do
    delete 'delete_food', on: :member
  end


  resources :recipes do
    member do
      patch 'toggle_privacy'
    end
  end

  resources :recipe_foods

  get '/shopping_list', to: 'shopping_list#show'

  get 'general_shopping_list', to: 'shopping_list#index'
  get 'public_recipes', to: 'public_recipes#index', as: 'public_recipes'

  get 'new_food', to: 'foods#new', as: 'custom_new_food'
  get 'new_recipe', to: 'recipes#new', as: 'custom_new_recipe'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :ingredients
  belongs_to :user
  validates :measurement_unit, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :food
end

app/models/measurement_unit.rb
class MeasurementUnit < ApplicationRecord
  has_many :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients, class_name: 'Ingredient'
  has_many :recipe_foods
  validates :name, presence: true

  def toggle_privacy
    self.public = !public
    save
  end

  def count_ingredients
    ingredients.count
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :recipes

  has_many :foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, :set_food, only: [:destroy]

  def new
    @food = Food.new
  end

  def index
    @foods = current_user.foods.includes(:ingredients)
    @food = current_user.foods.build
  end

  def show
    @food = Food.find(params[:id])
    redirect_to foods_path
  end

  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully added.' }
      else
        format.html { render :index }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food item was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete food item.'
      redirect_to foods_path
    end
  end

  def delete
    @food = current_user.foods.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      redirect_to foods_path, alert: 'Food deletion failed.'
    end
  end

  def delete_food
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end



  private

  def set_food
    @food = current_user.foods.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipe = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, flash: { success: 'Recipe saved successfully!' }
    else
      render :new, flash: { error: 'Recipe failed to save!' }
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    unless @recipe.user == current_user
      redirect_to recipes_path, flash: { error: 'You are not authorized to perform this action.' }
      return
    end

    if @recipe.destroy
      redirect_to recipes_path, flash: { success: 'Recipe deleted successfully!' }
    else
      redirect_to recipes_path, flash: { error: 'Failed to delete the recipe!' }
    end
  end

  def toggle_privacy
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.toggle_privacy
      redirect_to recipe_path(@recipe)
    else
      redirect_to root_path, alert: 'You do not have permission to do this.'
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def set_default_role
    self.role ||= :user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRGroupProject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Include Bootstrap 4 CSS from a valid CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to 'Recetas', authenticated_root_path  %>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
         <%= link_to 'Shopping List', general_shopping_list_path, class: 'nav-link' %>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if Recipe.any? %>
  <li class="nav-item">
    <%= link_to 'Public Recipes', public_recipes_path, class: 'nav-link' %>
  </li>
<% end %>

          <li class="nav-item">
            <%= link_to 'Add Food', new_food_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Recipe', new_recipe_path, class: 'nav-link' %>
          </li>
      </ul>
    </nav>

    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>